package nl.zeesoft.zsd.entity.entities.dutch;

import nl.zeesoft.zsd.BaseConfiguration;
import nl.zeesoft.zsd.EntityValueTranslator;
import nl.zeesoft.zsd.entity.EntityObject;

public class DutchCurrency extends EntityObject {
	@Override
	public String getLanguage() {
		return BaseConfiguration.LANG_NLD;
	}
	@Override
	public String getType() {
		return BaseConfiguration.TYPE_CURRENCY;
	}
	@Override
	public int getMaximumSymbols() {
		return 4;
	}
	@Override
	public void initialize(EntityValueTranslator translator) {
		super.initialize(translator);
		addCurrency("VS Dollar","USD");
		addCurrency("Dollar","USD");
		addCurrency("Canadese Dollar","CAD");
		addCurrency("Euro","EUR");
		addCurrency("Verenigde Arbische Emiraten Dirham","AED");
		addCurrency("Dirham","AED");
		addCurrency("Afghanistaanse Afghani","AFN");
		addCurrency("Afghani","AFN");
		addCurrency("Albanese Lek","ALL");
		addCurrency("Lek","ALL");
		addCurrency("Armeense Dram","AMD");
		addCurrency("Dram","AMD");
		addCurrency("Argentijnse Peso","ARS");
		addCurrency("Peso","ARS");
		addCurrency("Australische Dollar","AUD");
		addCurrency("Azerbeidzjaanse Manat","AZN");
		addCurrency("Manat","AZN");
		addCurrency("Bosnië en Herzegovina Mark","BAM");
		addCurrency("Mark","BAM");
		addCurrency("Bangladeshische Taka","BDT");
		addCurrency("Taka","BDT");
		addCurrency("Bulgaarse Lev","BGN");
		addCurrency("Lev","BGN");
		addCurrency("Bahreinse Dinar","BHD");
		addCurrency("Dinar","BHD");
		addCurrency("Burundische Franc","BIF");
		addCurrency("Franc","BIF");
		addCurrency("Bruneisische Dollar","BND");
		addCurrency("Boliviaanse Boliviano","BOB");
		addCurrency("Boliviano","BOB");
		addCurrency("Braziliaans Real","BRL");
		addCurrency("Real","BRL");
		addCurrency("Botswanische Pula","BWP");
		addCurrency("Pula","BWP");
		addCurrency("Wit Russische Roebel","BYR");
		addCurrency("Belizische Dollar","BZD");
		addCurrency("Congolese Franc","CDF");
		addCurrency("Zwitserse Franc","CHF");
		addCurrency("Chileense Peso","CLP");
		addCurrency("Chinese Yuan","CNY");
		addCurrency("Yuan","CNY");
		addCurrency("Colombiaanse Peso","COP");
		addCurrency("Costa Ricaanse Colón","CRC");
		addCurrency("Colón","CRC");
		addCurrency("Kaap Verdische Escudo","CVE");
		addCurrency("Escudo","CVE");
		addCurrency("Tsjechische Koruna","CZK");
		addCurrency("Koruna","CZK");
		addCurrency("Djiboutische Franc","DJF");
		addCurrency("Deense Krone","DKK");
		addCurrency("Krone","DKK");
		addCurrency("Dominicaanse Peso","DOP");
		addCurrency("Algeriaanse Dinar","DZD");
		addCurrency("Estoniaanse Kroon","EEK");
		addCurrency("Kroon","EEK");
		addCurrency("Egyptische Pond","EGP");
		addCurrency("Eritreische Nakfa","ERN");
		addCurrency("Nakfa","ERN");
		addCurrency("Ethiopische Birr","ETB");
		addCurrency("Birr","ETB");
		addCurrency("Britse Pond Sterling","GBP");
		addCurrency("Britse Pond","GBP");
		addCurrency("Pond Sterling","GBP");
		addCurrency("Pond","GBP");
		addCurrency("Georgische Lari","GEL");
		addCurrency("Lari","GEL");
		addCurrency("Ghaneese Cedi","GHS");
		addCurrency("Cedi","GHS");
		addCurrency("Guineaanse Franc","GNF");
		addCurrency("Guatemalaanse Quetzal","GTQ");
		addCurrency("Quetzal","GTQ");
		addCurrency("Hong Kong Dollar","HKD");
		addCurrency("Hondureese Lempira","HNL");
		addCurrency("Lempira","HNL");
		addCurrency("Kroatische Kuna","HRK");
		addCurrency("Kuna","HRK");
		addCurrency("Hongaarse Forint","HUF");
		addCurrency("Forint","HUF");
		addCurrency("Indonesische Rupiah","IDR");
		addCurrency("Rupiah","IDR");
		addCurrency("Israelische Sheqel","ILS");
		addCurrency("Sheqel","ILS");
		addCurrency("Indiaanse Rupee","INR");
		addCurrency("Rupee","INR");
		addCurrency("Iraakse Dinar","IQD");
		addCurrency("Iraanse Rial","IRR");
		addCurrency("Rial","IRR");
		addCurrency("Ijslandse Króna","ISK");
		addCurrency("Króna","ISK");
		addCurrency("Jamaicaanse Dollar","JMD");
		addCurrency("Jordaanische Dinar","JOD");
		addCurrency("Japanse Yen","JPY");
		addCurrency("Yen","JPY");
		addCurrency("Keniaanse Shilling","KES");
		addCurrency("Shilling","KES");
		addCurrency("Cambodjaanse Riel","KHR");
		addCurrency("Riel","KHR");
		addCurrency("Comoriaanse Franc","KMF");
		addCurrency("Zuid Koreaanse Won","KRW");
		addCurrency("Won","KRW");
		addCurrency("Koeweitische Dinar","KWD");
		addCurrency("Kazachstaanse Tenge","KZT");
		addCurrency("Tenge","KZT");
		addCurrency("Libaneese Pond","LBP");
		addCurrency("Sri Lankaanse Rupee","LKR");
		addCurrency("Lithouwse Litas","LTL");
		addCurrency("Litas","LTL");
		addCurrency("Letse Lats","LVL");
		addCurrency("Lats","LVL");
		addCurrency("Libische Dinar","LYD");
		addCurrency("Marokkaanse Dirham","MAD");
		addCurrency("Moldoviaanse Leu","MDL");
		addCurrency("Leu","MDL");
		addCurrency("Malageese Ariary","MGA");
		addCurrency("Ariary","MGA");
		addCurrency("Macedonische Denar","MKD");
		addCurrency("Denar","MKD");
		addCurrency("Myanma Kyat","MMK");
		addCurrency("Kyat","MMK");
		addCurrency("Macanese Pataca","MOP");
		addCurrency("Pataca","MOP");
		addCurrency("Mauritiaanse Rupee","MUR");
		addCurrency("Mexicaanse Peso","MXN");
		addCurrency("Maleisische Ringgit","MYR");
		addCurrency("Ringgit","MYR");
		addCurrency("Mozambiekse Metical","MZN");
		addCurrency("Metical","MZN");
		addCurrency("Namimbische Dollar","NAD");
		addCurrency("Nigeriaanse Naira","NGN");
		addCurrency("Naira","NGN");
		addCurrency("Nicaraguaanse Córdoba","NIO");
		addCurrency("Córdoba","NIO");
		addCurrency("Norwegische Krone","NOK");
		addCurrency("Nepalese Rupee","NPR");
		addCurrency("Nieuw Zeeland Dollar","NZD");
		addCurrency("Omanische Rial","OMR");
		addCurrency("Panameese Balboa","PAB");
		addCurrency("Balboa","PAB");
		addCurrency("Peruviaanse Nuevo Sol","PEN");
		addCurrency("Sol","PEN");
		addCurrency("Philipijnse Peso","PHP");
		addCurrency("Pakistaanse Rupee","PKR");
		addCurrency("Poolse Zloty","PLN");
		addCurrency("Zloty","PLN");
		addCurrency("Paraguayaanse Guarani","PYG");
		addCurrency("Guarani","PYG");
		addCurrency("Qatarische Rial","QAR");
		addCurrency("Roemeense Leu","RON");
		addCurrency("Servische Dinar","RSD");
		addCurrency("Russische Roebel","RUB");
		addCurrency("Roebel","RUB");
		addCurrency("Ruwandeese Franc","RWF");
		addCurrency("Saudische Riyal","SAR");
		addCurrency("Riyal","SAR");
		addCurrency("Sudaneese Pond","SDG");
		addCurrency("Zweedse Krona","SEK");
		addCurrency("Krona","SEK");
		addCurrency("Singaporeese Dollar","SGD");
		addCurrency("Somalische Shilling","SOS");
		addCurrency("Syriaanse Pond","SYP");
		addCurrency("Thaise Baht","THB");
		addCurrency("Baht","THB");
		addCurrency("Tunisische Dinar","TND");
		addCurrency("Tonganse Pa'anga","TOP");
		addCurrency("Pa'anga","TOP");
		addCurrency("Tonganse Paanga","TOP");
		addCurrency("Paanga","TOP");
		addCurrency("Turkse Lira","TRY");
		addCurrency("Lira","TRY");
		addCurrency("Trinidad en Tobago Dollar","TTD");
		addCurrency("Taiwaneese Dollar","TWD");
		addCurrency("Tanzaniaanse Shilling","TZS");
		addCurrency("Oekrainse Hryvnia","UAH");
		addCurrency("Hryvnia","UAH");
		addCurrency("Oegandeese Shilling","UGX");
		addCurrency("Oeruguayaanse Peso","UYU");
		addCurrency("Oezbekistaanse Som","UZS");
		addCurrency("Som","UZS");
		addCurrency("Venezuelaanse Bolívar","VEF");
		addCurrency("Bolívar","VEF");
		addCurrency("Vietnamese Dong","VND");
		addCurrency("Dong","VND");
		addCurrency("CFA Franc BEAC","XAF");
		addCurrency("BEAC","XAF");
		addCurrency("CFA Franc BCEAO","XOF");
		addCurrency("BCEAO","XOF");
		addCurrency("Jemense Rial","YER");
		addCurrency("Zuid Afrikaanse Rand","ZAR");
		addCurrency("Rand","ZAR");
		addCurrency("Zambiaanse Kwacha","ZMK");
		addCurrency("Kwacha","ZMK");
	}
	private void addCurrency(String name,String code) {
		addEntityValue(name.toLowerCase(),code,code);
	}
}
