package nl.zeesoft.zsds.resource;

import nl.zeesoft.zdk.ZStringBuilder;

public class EnvironmentJavaScript {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		script.append("var ZSDS = ZSDS || {};\n");
		
		script.append("ZSDS.environment = {};\n");
		script.append("ZSDS.environment.name = \"\";\n");
		script.append("ZSDS.environment.config = null;\n");
		script.append("ZSDS.environment.auto = true;\n");
		script.append("ZSDS.environment.getTestConfig = function() {\n");
		script.append("    ZSDS.xhr.getJSON(\"testConfig.json\",ZSDS.environment.getConfigCallback,ZSDS.environment.getConfigCallback);\n");
		script.append("};\n");
		script.append("ZSDS.environment.getConfigCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    ZSDS.environment.config = JSON.parse(response);\n");
		script.append("    ZSDS.environment.initializeSelector();\n");
		script.append("    ZSDS.environment.autoRefresh();\n");
		script.append("};\n");
		script.append("ZSDS.environment.initializeSelector = function() {\n");
		script.append("    var elem = window.document.getElementById(\"selector\");\n");
		script.append("    if (elem!=null && ZSDS.environment.config!=null) {\n");
		script.append("        var refresh = false;\n");
		script.append("        for (var i = 0; i < ZSDS.environment.config.environments.length; i++) {\n");
		script.append("            var option = document.createElement(\"option\");\n");
		script.append("            option.text = ZSDS.environment.config.environments[i].name;\n");
		script.append("            if (ZSDS.environment.name==\"\") {\n");
		script.append("                ZSDS.environment.name = option.text;\n");
		script.append("                refresh = true;\n");
		script.append("            }\n");
		script.append("            elem.add(option);\n");
		script.append("        }\n");
		script.append("        if (refresh) {\n");
		script.append("            ZSDS.environment.refreshEnvironment();\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.selectedEnvironment = function() {\n");
		script.append("    var elem = window.document.getElementById(\"selector\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        var sel = elem.options[elem.selectedIndex].value;\n");
		script.append("        ZSDS.environment.name = sel;\n");
		script.append("        ZSDS.environment.refreshEnvironment();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.refreshEnvironment = function() {\n");
		script.append("    if (ZSDS.environment.name!=\"\") {\n");
		script.append("        var environment = null;\n");
		script.append("        for (var i = 0; i < ZSDS.environment.config.environments.length; i++) {\n");
		script.append("            if (ZSDS.environment.config.environments[i].name==ZSDS.environment.name) {\n");
		script.append("                environment = ZSDS.environment.config.environments[i];\n");
		script.append("                break;\n");
		script.append("            }\n");
		script.append("        }\n");
		script.append("        var elemUrl = window.document.getElementById(\"url\");\n");
		script.append("        elemUrl.value = environment.url;\n");
		script.append("        var elemDir = window.document.getElementById(\"directory\");\n");
		script.append("        elemDir.value = ZSDS.environment.config.testCaseDir + environment.directory;\n");
		script.append("        setTimeout(function(){ ZSDS.environment.getSummary(); }, 200);\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.getSummary = function() {\n");
		script.append("    if (ZSDS.environment.name!=\"\") {\n");
		script.append("        var url = \"appTester.json?environment=\" + ZSDS.environment.name;\n");
		script.append("        ZSDS.xhr.getJSON(url,ZSDS.environment.getSummaryCallback,ZSDS.environment.getSummaryCallback);\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.getSummaryCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZSDS.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code) {\n");
		script.append("        ZSDS.environment.auto = true;\n");
		script.append("    } else {\n");
		script.append("        ZSDS.environment.auto = false;\n");
		script.append("    }\n");
		script.append("    elem = window.document.getElementById(\"summary\");\n");
		script.append("    elem.value = JSON.stringify(object,null,2);\n");
		script.append("};\n");
		script.append("ZSDS.environment.defaultCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZSDS.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    }\n");
		script.append("    setTimeout(function(){ ZSDS.environment.getSummary(); }, 200);\n");
		script.append("};\n");
		script.append("ZSDS.environment.test = function(xhr) {\n");
		script.append("    elem = window.document.getElementById(\"testCheck\");\n");
		script.append("    if (elem.checked) {\n");
		script.append("        elem.checked = false;\n");
		script.append("        if (ZSDS.environment.name==\"\") {\n");
		script.append("            alert(\"No environment selected\");\n");
		script.append("        } else {\n");
		script.append("            var url = \"appTester.json\";\n");
		script.append("            var body = {};\n");
		script.append("            body.action = \"test\";\n");
		script.append("            body.environmentName = ZSDS.environment.name;\n");
		script.append("            ZSDS.xhr.postJSON(url,body,ZSDS.environment.defaultCallback,ZSDS.environment.defaultCallback);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.reload = function(xhr) {\n");
		script.append("    elem = window.document.getElementById(\"reloadCheck\");\n");
		script.append("    if (elem.checked) {\n");
		script.append("        elem.checked = false;\n");
		script.append("        if (ZSDS.environment.name==\"\") {\n");
		script.append("            alert(\"No environment selected\");\n");
		script.append("        } else {\n");
		script.append("            var url = \"appTester.json\";\n");
		script.append("            var body = {};\n");
		script.append("            body.action = \"reload\";\n");
		script.append("            ZSDS.xhr.postJSON(url,body,ZSDS.environment.defaultCallback,ZSDS.environment.defaultCallback);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.environment.autoRefresh = function() {\n");
		script.append("    if (ZSDS.environment.auto) {\n");
		script.append("        ZSDS.environment.getSummary();\n");
		script.append("    }\n");
		script.append("    setTimeout(function(){ ZSDS.environment.autoRefresh(); }, 1000);\n");
		script.append("};\n");
		
		return script;
	}
}
