package nl.zeesoft.zsds.resource;

import nl.zeesoft.zdk.ZStringBuilder;

public class TestJavaScript {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		script.append("var ZSDS = ZSDS || {};\n");
		script.append("ZSDS.test = {};\n");
		script.append("ZSDS.test.client = new ZSDS.api.Client();\n");
		script.append("ZSDS.test.testCase = {};\n");
		script.append("ZSDS.test.testCase.name = \"RecordedTestCase\";\n");
		script.append("ZSDS.test.testCase.io = [];\n");
		script.append("ZSDS.test.getRequest = function() {\n");
		script.append("    ZSDS.xhr.getJSON(\"testDialogRequest.json\",ZSDS.test.getRequestCallback,ZSDS.test.getRequestCallback);\n");
		script.append("};\n");
		script.append("ZSDS.test.getRequestCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZSDS.xhr.parseResponseJSON(response);\n");
		script.append("    ZSDS.test.client = new ZSDS.api.Client(object);\n");
		script.append("    ZSDS.test.refreshRequest();\n");
		script.append("};\n");
		script.append("ZSDS.test.sendRequest = function() {\n");
		script.append("    var elem = window.document.getElementById(\"request\");\n");
		script.append("    if (elem!=null && elem.value.length>0) {\n");
		script.append("        elemResponse = window.document.getElementById(\"response\");\n");
		script.append("        if (elemResponse!=null) {\n");
		script.append("            elemResponse.value = \"Sending request ...\";\n");
		script.append("        }\n");
		script.append("        ZSDS.test.client.workingRequest = JSON.parse(elem.value);\n");
		script.append("        ZSDS.test.refreshRequest();\n");
		script.append("        ZSDS.test.client.workingRequest = JSON.parse(elem.value);\n");
		script.append("        ZSDS.test.addTestCaseIO(JSON.parse(elem.value));\n");
		script.append("        ZSDS.xhr.postJSON(\"dialogRequestHandler.json\",ZSDS.test.client.workingRequest,ZSDS.test.sendRequestCallback,ZSDS.test.sendRequestCallback);\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.test.sendRequestCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var obj = JSON.parse(response);\n");
		script.append("    if (!obj.code) {\n");
		script.append("        ZSDS.test.client.processRequestResponse(obj);\n");
		script.append("        ZSDS.test.addTestCaseIOResponse(obj);\n");
		script.append("    }\n");
		script.append("    var object = ZSDS.xhr.parseResponseJSON(response);\n");
		script.append("    ZSDS.test.showResponse(object);\n");
		script.append("};\n");
		script.append("ZSDS.test.focusInput = function() {\n");
		script.append("    var elem = window.document.getElementById(\"input\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.blur();\n");
		script.append("        elem.focus();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.test.refreshRequest = function() {\n");
		script.append("    var elem = window.document.getElementById(\"request\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        var elemPrompt = window.document.getElementById(\"prompt\");\n");
		script.append("        var elemInput = window.document.getElementById(\"input\");\n");
		script.append("        if (ZSDS.test.client.workingRequest!=null) {\n");
		script.append("            ZSDS.test.client.workingRequest.prompt = elemPrompt.value;\n");
		script.append("            ZSDS.test.client.workingRequest.input = elemInput.value;\n");
		script.append("            elem.value = JSON.stringify(ZSDS.test.client.workingRequest,null,2);\n");
		script.append("        } else {\n");
		script.append("            elem.value = \"\";\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("}\n");
		script.append("ZSDS.test.showResponse = function(object) {\n");
		script.append("    var elem = window.document.getElementById(\"response\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        if (typeof(object.contextOutputs)!==\"undefined\" && typeof(object.contextOutputs[0])!==\"undefined\") {\n");
		script.append("            var elemOutput = window.document.getElementById(\"output\");\n");
		script.append("            var elemPrompt = window.document.getElementById(\"prompt\");\n");
		script.append("            var elemInput = window.document.getElementById(\"input\");\n");
		script.append("            if (elemOutput!=null && elemPrompt!=null && elemInput!=null) {\n");
		script.append("                elemOutput.value = object.contextOutputs[0].output;\n");
		script.append("                elemPrompt.value = object.contextOutputs[0].prompt;\n");
		script.append("                elemInput.value = \"\";\n");
		script.append("            }\n");
		script.append("        } else if (object.error) {\n");
		script.append("            var elemOutput = window.document.getElementById(\"output\");\n");
		script.append("            if (elemOutput!=null) {\n");
		script.append("                elemOutput.value = object.error;\n");
		script.append("            }\n");
		script.append("        }\n");
		script.append("        ZSDS.test.refreshRequest();\n");
		script.append("        var response = JSON.stringify(object,null,2);\n");
		script.append("        response = response.replace(/\\\\n/g,\"\\n\");\n");
		script.append("        elem.value = response;\n");
		script.append("        elem.scrollTop = elem.scrollHeight;\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.test.addTestCaseIO = function(request) {\n");
		script.append("    if (!ZSDS.test.client.workingRequest.randomizeOutput) {\n");
		script.append("        var obj = {};\n");
		script.append("        obj.request = request;\n");
		script.append("        ZSDS.test.testCase.io[ZSDS.test.testCase.io.length] = obj;\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDS.test.addTestCaseIOResponse = function(response) {\n");
		script.append("    if (!ZSDS.test.client.workingRequest.randomizeOutput) {\n");
		script.append("        response.debugLog = \"\";\n");
		script.append("        var obj = ZSDS.test.testCase.io[(ZSDS.test.testCase.io.length - 1)];\n");
		script.append("        obj.expectedResponse = response;\n");
		script.append("        elemResponse = window.document.getElementById(\"testCase\");\n");
		script.append("        if (elemResponse!=null) {\n");
		script.append("            elemResponse.value = JSON.stringify(ZSDS.test.testCase,null,2);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		
		return script;
	}
}
