package nl.zeesoft.zsda.mod.resource;

import nl.zeesoft.zdk.ZStringBuilder;
import nl.zeesoft.zodb.db.DatabaseRequest;
import nl.zeesoft.zodb.mod.ModZODB;
import nl.zeesoft.zodb.mod.handler.JsonZODBRequestHandler;
import nl.zeesoft.zsda.mod.ModZSDA;
import nl.zeesoft.zsda.mod.handler.JsonZSDAGridConfigHandler;

public class JavaScriptZSDAGridMonitor {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		String pathZSDA = "../" + ModZSDA.NAME + JsonZSDAGridConfigHandler.PATH;
		String pathZODB = "../" + ModZODB.NAME + JsonZODBRequestHandler.PATH;
		
		script.append("var ZSDA = ZSDA || {};\n");
		script.append("ZSDA.monitor = ZSDA.monitor || {};\n");
		script.append("ZSDA.monitor.grid = null;\n");
		script.append("ZSDA.monitor.logs = [];\n");
		script.append("ZSDA.monitor.dateTime = 0;\n");
		script.append("ZSDA.monitor.id = 0;\n");
		script.append("ZSDA.monitor.get = function() {\n");
		script.append("    var request = {};\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZSDA + "\",request,ZSDA.monitor.getCallback,ZSDA.monitor.getCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getCallback = function(xhr) {\n");
		script.append("    console.log(\"GOT GRID\");\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.get(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        ZSDA.monitor.grid = object;\n");
		script.append("        console.log(\"LIST LOGS\");\n");
		script.append("        ZSDA.monitor.listLogs();\n");
		//script.append("        elem = window.document.getElementById(\"columnIO\");\n");
		//script.append("        if (elem!=null) {\n");
		//script.append("            elem.innerHTML = ZSDA.monitor.getIOTable();\n");
		//script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogs = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_LIST + "\";\n");
		script.append("    request.index = \"" + ModZSDA.NAME + "/Logs/:dateTime\";\n");
		script.append("    request.operator = \"" + DatabaseRequest.OP_GREATER + "\";\n");
		script.append("    request.value = ZSDA.monitor.dateTime;\n");
		script.append("    request.max = 1;\n");
		script.append("    request.ascending = false;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    console.log(\"REQUEST: \" + JSON.stringify(request,null,2));\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.listLogsCallback,ZSDA.monitor.listLogsCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogsCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.listLogs(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            var log = object.results[name];\n");
		script.append("            ZSDA.monitor.id = log.id;\n");
		script.append("        }\n");
		script.append("        ZSDA.monitor.getLog();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLog = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_GET + "\";\n");
		script.append("    request.id = ZSDA.monitor.id;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    console.log(\"REQUEST: \" + JSON.stringify(request,null,2));\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.getLogCallback,ZSDA.monitor.getLogCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getLog(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            var log = object.results[name];\n");
		script.append("            console.log(log);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogs = function() {\n");
		script.append("    dateTime = ZSDA.monitor.dateTime;\n");
		script.append("    if (dateTime==0) {\n");
		script.append("        var date = new Date();\n");
		script.append("        dateTime = date.getTime() - (3600 * 2);\n");
		script.append("    }\n");
		script.append("    console.log(\"GET LOGS!\");\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_GET + "\";\n");
		script.append("    request.index = \"" + ModZSDA.NAME + "/Logs/:dateTime\";\n");
		script.append("    request.invert = false;\n");
		script.append("    request.operator = \"" + DatabaseRequest.OP_GREATER + "\";\n");
		script.append("    request.value = 0;\n");
		script.append("    request.readTimeOutSeconds = 10;\n");
		script.append("    console.log(\"REQUEST: \" + JSON.stringify(request,null,2));\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.getLogsCallback,ZSDA.monitor.getLogsCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogsCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getLogs(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            var log = object.results[name];\n");
		script.append("            console.log(log);\n");
		script.append("        }\n");
		//script.append("        elem = window.document.getElementById(\"columnIO\");\n");
		//script.append("        if (elem!=null) {\n");
		//script.append("            elem.innerHTML = ZSDA.monitor.getIOTable();\n");
		//script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.onload = function() {\n");
		script.append("    ZSDA.monitor.get();\n");
		script.append("};\n");
		
		return script;
	}
}
