package nl.zeesoft.zsda.mod.resource;

import nl.zeesoft.zdk.ZStringBuilder;
import nl.zeesoft.zodb.db.DatabaseRequest;
import nl.zeesoft.zodb.mod.ModZODB;
import nl.zeesoft.zodb.mod.handler.JsonZODBRequestHandler;
import nl.zeesoft.zsda.mod.ModZSDA;
import nl.zeesoft.zsda.mod.handler.JsonZSDAGridConfigHandler;
import nl.zeesoft.zsda.mod.handler.JsonZSDAGridHistoryHandler;

public class JavaScriptZSDAGridMonitor {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		String pathZSDAConfig = "../" + ModZSDA.NAME + JsonZSDAGridConfigHandler.PATH;
		String pathZSDAHistory = "../" + ModZSDA.NAME + JsonZSDAGridHistoryHandler.PATH;
		String pathZODB = "../" + ModZODB.NAME + JsonZODBRequestHandler.PATH;
		
		script.append("var ZSDA = ZSDA || {};\n");
		script.append("ZSDA.monitor = ZSDA.monitor || {};\n");
		script.append("ZSDA.monitor.grid = null;\n");
		script.append("ZSDA.monitor.history = null;\n");
		script.append("ZSDA.monitor.logs = [];\n");
		script.append("ZSDA.monitor.dateTime = 0;\n");
		script.append("ZSDA.monitor.id = 0;\n");
		script.append("ZSDA.monitor.log = {};\n");
		script.append("ZSDA.monitor.get = function() {\n");
		script.append("    var request = {};\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZSDAConfig + "\",request,ZSDA.monitor.getCallback,ZSDA.monitor.getCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.get(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        ZSDA.monitor.grid = object;\n");
		script.append("        ZSDA.monitor.listLogs();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getHistory = function() {\n");
		script.append("    var request = {};\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZSDAHistory + "\",request,ZSDA.monitor.getHistoryCallback,ZSDA.monitor.getHistoryCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getHistoryCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getHistory(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getHistory(); },5000);\n");
		script.append("        ZSDA.monitor.history = object;\n");
		script.append("        ZSDA.monitor.showHistory();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.showHistory = function() {\n");
		script.append("    elem = window.document.getElementById(\"history\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.innerHTML = ZSDA.monitor.getHistoryTable();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getHistoryTable = function() {\n");
		script.append("    var history = ZSDA.monitor.history;\n");
		script.append("    var length = 50;\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table class=\"histTable\">';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr>';\n");
		script.append("    for (var name in history.results) {\n");
		script.append("        var res = history.results[name];\n");
		script.append("        var val = -1;\n");
		script.append("        var pred = -1;\n");
		script.append("        var anom = -1;\n");
		script.append("        if (typeof(res.relVal)!==\"undefined\") {\n");
		script.append("            val = Math.round(res.relVal * length);\n");
		script.append("        }\n");
		script.append("        if (typeof(res.relPred)!==\"undefined\") {\n");
		script.append("            pred = Math.round(res.relPred * length);\n");
		script.append("        }\n");
		script.append("        if (typeof(res.anom)!==\"undefined\") {;\n");
		script.append("            anom = Math.round(res.anom * length);\n");
		script.append("        }\n");
		script.append("        html += '<tr class=\"histTr\">';\n");
		script.append("        for (var i = 0; i <= length; i++) {\n");
		script.append("            var color = \"white\";\n");
		script.append("            if (i==val) {\n");
		script.append("                color = \"blue\";\n");
		script.append("            }\n");
		script.append("            if (i==pred) {\n");
		script.append("                color = \"green\";\n");
		script.append("            }\n");
		script.append("            if (i==anom) {\n");
		script.append("                color = \"red\";\n");
		script.append("            }\n");
		script.append("            html += '<td class=\"histTd ' + color + '\">';\n");
		script.append("            html += '.';\n");
		script.append("            html += '</td>';\n");
		script.append("        }\n");
		script.append("        html += '</tr>';\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogs = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_LIST + "\";\n");
		script.append("    request.index = \"" + ModZSDA.NAME + "/Logs/:dateTime\";\n");
		script.append("    request.operator = \"" + DatabaseRequest.OP_GREATER + "\";\n");
		script.append("    request.value = ZSDA.monitor.dateTime;\n");
		script.append("    request.max = 1;\n");
		script.append("    request.ascending = false;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.listLogsCallback,ZSDA.monitor.listLogsCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogsCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.listLogs(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else if (!object.results) {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.listLogs(); },1000);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            var res = object.results[name];\n");
		script.append("            ZSDA.monitor.id = res.id;\n");
		script.append("            ZSDA.monitor.getLog();\n");
		script.append("            break;\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLog = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_GET + "\";\n");
		script.append("    request.id = ZSDA.monitor.id;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.getLogCallback,ZSDA.monitor.getLogCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getLog(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            ZSDA.monitor.log = object.results[name].object;\n");
		script.append("            ZSDA.monitor.dateTime = ZSDA.monitor.log.dateTime;\n");
		script.append("            setTimeout(function() { ZSDA.monitor.listLogs(); },5000);\n");
		script.append("            ZSDA.monitor.showLog();\n");
		script.append("            break;\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.showLog = function() {\n");
		script.append("    elem = window.document.getElementById(\"columnIO\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.innerHTML = ZSDA.monitor.getColumnIOTable();\n");
		script.append("    }\n");
		script.append("    elem = window.document.getElementById(\"classifications\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.innerHTML = ZSDA.monitor.getClassificationsTable();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getClassificationsTable = function() {\n");
		script.append("    var log = ZSDA.monitor.log;\n");
		script.append("    var html = '';\n");
		script.append("    if (log.classifications.length==0) {\n");
		script.append("        return html;\n");
		script.append("    }\n");
		script.append("    html += '<br />';\n");
		script.append("    html += '<b>Classifications</b><br />';\n");
		script.append("    html += '<table class=\"grid\">';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr class=\"grid\">';\n");
		script.append("    html += '<td class=\"grid\">';\n");
		script.append("    html += '<b>';\n");
		script.append("    html += 'Key';\n");
		script.append("    html += '</b>';\n");
		script.append("    html += '</td>';\n");
		script.append("    html += '<td class=\"grid\">';\n");
		script.append("    html += '<b>';\n");
		script.append("    html += 'Steps';\n");
		script.append("    html += '</b>';\n");
		script.append("    html += '</td>';\n");
		script.append("    html += '<td class=\"grid\">';\n");
		script.append("    html += '<b>';\n");
		script.append("    html += 'Winner(s)';\n");
		script.append("    html += '</b>';\n");
		script.append("    html += '</td>';\n");
		script.append("    html += '</tr>';\n");
		script.append("    for (var name in log.classifications) {\n");
		script.append("        var classification = log.classifications[name];\n");
		script.append("        var prediction = \"\";\n");
		script.append("        for (var index in classification.mostCountedValues) {\n");
		script.append("            if (prediction.length>0) {\n");
		script.append("                prediction += \", \";\n");
		script.append("            }\n");
		script.append("            prediction += \"\" + classification.mostCountedValues[index];\n");
		script.append("        }\n");
		script.append("        html += '<tr class=\"grid\">';\n");
		script.append("        html += '<td class=\"grid\">';\n");
		script.append("        html += classification.valueKey;\n");
		script.append("        html += '</td>';\n");
		script.append("        html += '<td class=\"grid\" align=\"right\">';\n");
		script.append("        html += classification.steps;\n");
		script.append("        html += '</td>';\n");
		script.append("        html += '<td class=\"grid\" align=\"right\">';\n");
		script.append("        html += prediction;\n");
		script.append("        html += '</td>';\n");
		script.append("        html += '</tr>';\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnInputClassName = function(log,columnIndex) {\n");
		script.append("    var r = \"\";\n");
		script.append("    var c = 0;\n");
		script.append("    for (var name1 in log.request) {\n");
		script.append("        for (var name2 in log.request[name1].values) {\n");
		script.append("            r = log.request[name1].values[name2].className;\n");
		script.append("            if (c==columnIndex) {\n");
		script.append("                break;\n");
		script.append("            }\n");
		script.append("            c++;\n");
		script.append("        }\n");
		script.append("        break;\n");
		script.append("    }\n");
		script.append("    return r;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnIOTable = function() {\n");
		script.append("    var grid = ZSDA.monitor.grid;\n");
		script.append("    var log = ZSDA.monitor.log;\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table class=\"grid\">';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr class=\"grid\">';\n");
		script.append("    for (var c = 0; c < grid.columns; c++) {\n");
		script.append("        var id = ZSDA.config.getColumnId(0,c);\n");
		script.append("        var config = ZSDA.config.getConfigurationByColumnId(grid,id);\n");
		script.append("        var align = \"\";\n");
		script.append("        if (ZSDA.monitor.getColumnInputClassName(log,c)!=\"String\") {\n");
		script.append("            align='align=\"right\" ';\n");
		script.append("        }\n");
		script.append("        html += '<td ' +  align + 'class=\"grid\">';\n");
		script.append("        if (config!=null) {\n");
		script.append("            html += config.valueKey;\n");
		script.append("        }\n");
		script.append("        html += '</td>';\n");
		script.append("    }\n");
		script.append("    html += '</tr>';\n");
		script.append("    html += '<tr class=\"grid\">';\n");
		script.append("    for (var name1 in log.request) {\n");
		script.append("        for (var name2 in log.request[name1].values) {\n");
		script.append("            var input = log.request[name1].values[name2];\n");
		script.append("            var align = \"\";\n");
		script.append("            if (input.className!=\"String\") {\n");
		script.append("                align='align=\"right\" ';\n");
		script.append("            }\n");
		script.append("            html += '<td ' +  align + 'class=\"grid\">';\n");
		script.append("            html += input.value;\n");
		script.append("            html += '</td>';\n");
		script.append("        }\n");
		script.append("        break;\n");
		script.append("    }\n");
		script.append("    html += '</tr>';\n");
		script.append("    for (var r = 0; r < grid.rows; r++) {\n");
		script.append("        html += '<tr>';\n");
		script.append("        for (var c = 0; c < grid.columns; c++) {\n");
		script.append("            var id = ZSDA.config.getColumnId(r,c);\n");
		script.append("            var config = ZSDA.config.getConfigurationByColumnId(grid,id);\n");
		script.append("            html += '<td valign=\"top\" class=\"grid\">';\n");
		script.append("            if (config!=null) {\n");
		script.append("                html += ZSDA.monitor.getColumnTable(config,log.columnOutputs);\n");
		script.append("            }\n");
		script.append("            html += '</td>';\n");
		script.append("        }\n");
		script.append("        html += '</tr>';\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnOutputsByColumnId = function(columnOutputs,columnId) {\n");
		script.append("    var sdrs\n");
		script.append("    for (var name in columnOutputs) {\n");
		script.append("        var output = columnOutputs[name];\n");
		script.append("        if (output.columnId==columnId) {\n");
		script.append("            sdrs = output.sdrs\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("    return sdrs;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnTable = function(configuration,columnOutputs) {\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table>';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr>';\n");
		script.append("    html += '<td>';\n");
		script.append("    html += '<b>';\n");
		script.append("    html += configuration['columnId'];\n");
		script.append("    html += '&nbsp;';\n");
		script.append("    html += configuration['className'];\n");
		script.append("    html += '</b>';\n");
		script.append("    html += '</td>';\n");
		script.append("    html += '</tr>';\n");
		script.append("    var sdrs = ZSDA.monitor.getColumnOutputsByColumnId(columnOutputs,configuration['columnId']);\n");
		script.append("    for (var name in sdrs) {\n");
		script.append("        html += '<tr>';\n");
		script.append("        html += '<td>';\n");
		script.append("        var sdr = sdrs[name];\n");
		script.append("        html += ZSDA.monitor.getSDRTable(sdr);\n");
		script.append("        html += '</td>';\n");
		script.append("        html += '</tr>';\n");
		script.append("        break;\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getSDRTable = function(sdr) {\n");
		script.append("    var elems = sdr.split(\",\");\n");
		script.append("    var html = '';\n");
		script.append("    if (elems.length>1) {\n");
		script.append("        var length = elems[0];\n");
		script.append("        html += '<table class=\"sdrTable\">';\n");
		script.append("        html += '<tbody>';\n");
		script.append("        var sizeX = Math.sqrt(length);\n");
		script.append("        if (sizeX % 1 > 0) {\n");
		script.append("            sizeX = sizeX - (sizeX % 1);\n");
		script.append("        }\n");
		script.append("        var sizeY = sizeX;\n");
		script.append("        if (sizeX * sizeY < length) {\n");
		script.append("            sizeX++;\n");
		script.append("        }\n");
		script.append("        if (sizeX * sizeY < length) {\n");
		script.append("            sizeY++;\n");
		script.append("        }\n");
		script.append("        var i = 0;\n");
		script.append("        for (var y = 0; y < sizeY; y++) {\n");
		script.append("            html += '<tr class=\"sdrTr\">';\n");
		script.append("            for (var x = 0; x < sizeX; x++) {\n");
		script.append("                var on = false;\n");
		script.append("                var cls = \"white\";\n");
		script.append("                for (var b = 1; b < elems.length; b++) {\n");
		script.append("                    if (elems[b]==i) {\n");
		script.append("                        on = true;\n");
		script.append("                        cls = \"blue\";\n");
		script.append("                        break;\n");
		script.append("                    }\n");
		script.append("                }\n");
		script.append("                html += '<td class=\"sdrTd ' + cls + '\">';\n");
		script.append("                html += '.';\n");
		script.append("                html += '</td>';\n");
		script.append("                i++;\n");
		script.append("                if (i==length) {\n");
		script.append("                    break;\n");
		script.append("                }\n");
		script.append("            }\n");
		script.append("            html += '</tr>';\n");
		script.append("        }\n");
		script.append("        html += '</tbody>';\n");
		script.append("        html += '</table>';\n");
		script.append("    }\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.onload = function() {\n");
		script.append("    ZSDA.monitor.get();\n");
		script.append("    ZSDA.monitor.getHistory();\n");
		script.append("};\n");
		
		return script;
	}
}
