package nl.zeesoft.zsda.mod.resource;

import nl.zeesoft.zdk.ZStringBuilder;
import nl.zeesoft.zodb.db.DatabaseRequest;
import nl.zeesoft.zodb.mod.ModZODB;
import nl.zeesoft.zodb.mod.handler.JsonZODBRequestHandler;
import nl.zeesoft.zsda.mod.ModZSDA;
import nl.zeesoft.zsda.mod.handler.JsonZSDAGridConfigHandler;

public class JavaScriptZSDAGridMonitor {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		String pathZSDA = "../" + ModZSDA.NAME + JsonZSDAGridConfigHandler.PATH;
		String pathZODB = "../" + ModZODB.NAME + JsonZODBRequestHandler.PATH;
		
		script.append("var ZSDA = ZSDA || {};\n");
		script.append("ZSDA.monitor = ZSDA.monitor || {};\n");
		script.append("ZSDA.monitor.grid = null;\n");
		script.append("ZSDA.monitor.logs = [];\n");
		script.append("ZSDA.monitor.dateTime = 0;\n");
		script.append("ZSDA.monitor.id = 0;\n");
		script.append("ZSDA.monitor.log = {};\n");
		script.append("ZSDA.monitor.get = function() {\n");
		script.append("    var request = {};\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZSDA + "\",request,ZSDA.monitor.getCallback,ZSDA.monitor.getCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.get(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        ZSDA.monitor.grid = object;\n");
		script.append("        ZSDA.monitor.listLogs();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogs = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_LIST + "\";\n");
		script.append("    request.index = \"" + ModZSDA.NAME + "/Logs/:dateTime\";\n");
		script.append("    request.operator = \"" + DatabaseRequest.OP_GREATER + "\";\n");
		script.append("    request.value = ZSDA.monitor.dateTime;\n");
		script.append("    request.max = 1;\n");
		script.append("    request.ascending = false;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.listLogsCallback,ZSDA.monitor.listLogsCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.listLogsCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.listLogs(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            var res = object.results[name];\n");
		script.append("            ZSDA.monitor.id = res.id;\n");
		script.append("            ZSDA.monitor.getLog();\n");
		script.append("            break;\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLog = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + DatabaseRequest.TYPE_GET + "\";\n");
		script.append("    request.id = ZSDA.monitor.id;\n");
		script.append("    request.readTimeOutSeconds = 60;\n");
		script.append("    ZODB.xhr.postJSON(\"" + pathZODB + "\",request,ZSDA.monitor.getLogCallback,ZSDA.monitor.getLogCallback);\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.code==\"503\") {\n");
		script.append("        setTimeout(function() { ZSDA.monitor.getLog(); },1000);\n");
		script.append("    } else if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        for (var name in object.results) {\n");
		script.append("            ZSDA.monitor.log = object.results[name].object;\n");
		script.append("            ZSDA.monitor.dateTime = ZSDA.monitor.log.dateTime;\n");
		script.append("            setTimeout(function() { ZSDA.monitor.listLogs(); },5000);\n");
		script.append("            ZSDA.monitor.showLog();\n");
		script.append("            break;\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.showLog = function() {\n");
		script.append("    elem = window.document.getElementById(\"columnIO\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.innerHTML = ZSDA.monitor.getLogTable();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getLogTable = function() {\n");
		script.append("    var grid = ZSDA.monitor.grid;\n");
		script.append("    var log = ZSDA.monitor.log;\n");
		//script.append("    console.log(JSON.stringify(log,null,2));\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table>';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr>';\n");
		script.append("    for (var name1 in log.request) {\n");
		script.append("        for (var name2 in log.request[name1].values) {\n");
		script.append("            html += '<td>';\n");
		script.append("            html += log.request[name1].values[name2].value;\n");
		script.append("            html += '</td>';\n");
		script.append("        }\n");
		script.append("        break;\n");
		script.append("    }\n");
		script.append("    html += '</tr>';\n");
		script.append("    for (var r = 0; r < grid.rows; r++) {\n");
		script.append("        html += '<tr>';\n");
		script.append("        for (var c = 0; c < grid.columns; c++) {\n");
		script.append("            var id = ZSDA.config.getColumnId(r,c);\n");
		script.append("            var config = ZSDA.config.getConfigurationByColumnId(grid,id);\n");
		script.append("            html += '<td valign=\"top\">';\n");
		script.append("            if (config!=null) {\n");
		script.append("                html += ZSDA.monitor.getColumnTable(config,log.columnOutputs);\n");
		script.append("            }\n");
		script.append("            html += '</td>';\n");
		script.append("        }\n");
		script.append("        html += '</tr>';\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnOutputsByColumnId = function(columnOutputs,columnId) {\n");
		script.append("    var sdrs\n");
		script.append("    for (var name in columnOutputs) {\n");
		script.append("        var output = columnOutputs[name];\n");
		script.append("        if (output.columnId==columnId) {\n");
		script.append("            sdrs = output.sdrs\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("    return sdrs;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getColumnTable = function(configuration,columnOutputs) {\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table>';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    html += '<tr>';\n");
		script.append("    html += '<td>';\n");
		script.append("    html += configuration['columnId'];\n");
		script.append("    html += '&nbsp;';\n");
		script.append("    html += configuration['className'];\n");
		script.append("    html += '</td>';\n");
		script.append("    html += '</tr>';\n");
		script.append("    var sdrs = ZSDA.monitor.getColumnOutputsByColumnId(columnOutputs,configuration['columnId']);\n");
		script.append("    for (var name in sdrs) {\n");
		script.append("        html += '<tr>';\n");
		script.append("        html += '<td>';\n");
		script.append("        var sdr = sdrs[name];\n");
		script.append("        html += ZSDA.monitor.getSDRTable(sdr);\n");
		script.append("        html += '</td>';\n");
		script.append("        html += '</tr>';\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.getSDRTable = function(sdr) {\n");
		script.append("    var elems = sdr.split(\",\");\n");
		script.append("    var html = '';\n");
		script.append("    html += '<table>';\n");
		script.append("    html += '<tbody>';\n");
		script.append("    if (elems.length>1) {\n");
		script.append("        var length = elems[0];\n");
		script.append("        var sizeX = Math.sqrt(length);\n");
		script.append("        if (sizeX % 1 > 0) {\n");
		script.append("            sizeX = sizeX - (sizeX % 1) + 1;\n");
		script.append("        }\n");
		script.append("        var sizeY = sizeX;\n");
		script.append("        var i = 0;\n");
		script.append("        for (var y = 0; y < sizeY; y++) {\n");
		script.append("            html += '<tr>';\n");
		script.append("            for (var x = 0; x < sizeX; x++) {\n");
		script.append("                html += '<td>';\n");
		script.append("                var f = false;\n");
		script.append("                for (var b = 1; b < elems.length; b++) {\n");
		script.append("                    if (elems[b]==i) {\n");
		script.append("                        html += '1';\n");
		script.append("                        f = true;\n");
		script.append("                        break;\n");
		script.append("                    }\n");
		script.append("                }\n");
		script.append("                if (!f) {\n");
		script.append("                    html += '0';\n");
		script.append("                }\n");
		script.append("                html += '</td>';\n");
		script.append("                i++;\n");
		script.append("                if (i==length) {\n");
		script.append("                    break;\n");
		script.append("                }\n");
		script.append("            }\n");
		script.append("            html += '</tr>';\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("    html += '</tbody>';\n");
		script.append("    html += '</table>';\n");
		script.append("    return html;\n");
		script.append("};\n");
		script.append("ZSDA.monitor.onload = function() {\n");
		script.append("    ZSDA.monitor.get();\n");
		script.append("};\n");
		
		return script;
	}
}
