package nl.zeesoft.zids.server.resource;

import nl.zeesoft.zodb.file.HTMLFile;

public class RscDialogSpeakerHtml extends RscHtmlObject {
	public RscDialogSpeakerHtml(String title, String backgroundColor) {
		super(title, backgroundColor);
	}

	@Override
	public StringBuilder toStringBuilder() {
		StringBuilder header = new StringBuilder();
		header.append("<script type=\"text/javascript\">\n");
		header.append("var ZIDS = ZIDS || {};\n");
		header.append("\n");
		header.append("ZIDS.speaker = {};\n");
		header.append("ZIDS.speaker.sessionId = null;\n");
		header.append("ZIDS.speaker.sessionStarted = false;\n");
		header.append("ZIDS.speaker.log = \"\";\n");
		header.append("ZIDS.speaker.logIncludingThoughts = \"\";\n");
		header.append("ZIDS.speaker.showThoughts = false;\n");
		header.append("ZIDS.speaker.previousInput = \"\";\n");
		header.append("ZIDS.speaker.currentInput = \"\";\n");
		header.append("ZIDS.speaker.postRequestCallback = function(xhr) {\n");
		header.append("    var response = xhr.responseText;\n");
		header.append("    var object = ZIDS.xhr.parseResponseJSON(response);\n");
		header.append("    if (ZIDS.speaker.sessionId!=object.sessionId) {\n");
		header.append("        ZIDS.speaker.sessionId = object.sessionId;\n");
		header.append("        ZIDS.speaker.updatedSessionId();\n");
		header.append("    }\n");
		header.append("    ZIDS.speaker.sessionStarted = true;\n");
		header.append("    document.getElementById(\"context\").value = \"\";\n");
		header.append("    document.getElementById(\"input\").value = \"\";\n");
		header.append("    ZIDS.speaker.log = \"\";\n");
		header.append("    ZIDS.speaker.logIncludingThoughts = \"\";\n");
		header.append("    if (object.log) {\n");
		header.append("        ZIDS.speaker.log = object.log;\n");
		header.append("    }\n");
		header.append("    if (object.logIncludingThoughts) {\n");
		header.append("        ZIDS.speaker.logIncludingThoughts = object.logIncludingThoughts;\n");
		header.append("    }\n");
		header.append("    if (object.type==\"SessionEndedRequest\") {\n");
		header.append("        ZIDS.speaker.generateSessionId();\n");
		header.append("    }\n");
		header.append("    if (object.error) {\n");
		header.append("        alert(object.error);\n");
		header.append("    }\n");
		header.append("    ZIDS.speaker.toggleShowThoughts();\n");
		header.append("    ZIDS.speaker.focusInput();\n");
		header.append("};\n");
		header.append("ZIDS.speaker.updatedSessionId = function() {\n");
		header.append("    if (ZIDS.speaker.sessionId!=null) {\n");
		header.append("        document.getElementById(\"sessionId\").value = ZIDS.speaker.sessionId;\n");
		header.append("    }\n");
		header.append("};\n");
		header.append("ZIDS.speaker.generateSessionId = function() {\n");
		header.append("    ZIDS.speaker.sessionId = \"\" + (new Date()).getTime();\n");
		header.append("    ZIDS.speaker.sessionStarted = false;\n");
		header.append("    ZIDS.speaker.updatedSessionId();\n");
		header.append("    return ZIDS.speaker.sessionId;\n");
		header.append("};\n");
		header.append("ZIDS.speaker.newSession = function() {\n");
		header.append("    if (ZIDS.speaker.sessionId!=null && ZIDS.speaker.sessionStarted) {\n");
		header.append("        var request = ZIDS.dialog.getNewSessionEndedRequest(ZIDS.speaker.sessionId);\n");
		header.append("        ZIDS.xhr.postJSON(\"../dialog/\",JSON.stringify(request),ZIDS.speaker.postRequestCallback);\n");
		header.append("    } else {\n");
		header.append("        ZIDS.speaker.generateSessionId();\n");
		header.append("    }\n");
		header.append("};\n");
		header.append("ZIDS.speaker.toggleShowThoughts = function() {\n");
		header.append("    var textarea = document.getElementById(\"log\");\n");
		header.append("    if (ZIDS.speaker.isShowThoughts()) {\n");
		header.append("        textarea.value = ZIDS.speaker.logIncludingThoughts;\n");
		header.append("    } else {\n");
		header.append("        textarea.value = ZIDS.speaker.log;\n");
		header.append("    }\n");
		header.append("    textarea.scrollTop = textarea.scrollHeight;\n");
		header.append("};\n");
		header.append("ZIDS.speaker.isShowThoughts = function() {\n");
		header.append("    return document.getElementById(\"showThoughts\").checked;\n");
		header.append("};\n");
		header.append("ZIDS.speaker.postRequest = function() {\n");
		header.append("    var input = document.getElementById(\"input\").value;\n");
		header.append("    if (input==null || input.trim().length==0) {\n");
		header.append("        return;\n");
		header.append("    }\n");
		header.append("    ZIDS.speaker.previousInput = input;\n");
		header.append("    ZIDS.speaker.currentInput = \"\";\n");
		header.append("    var sessionId = document.getElementById(\"sessionId\").value;\n");
		header.append("    var context = document.getElementById(\"context\").value;\n");
		header.append("    var input = document.getElementById(\"input\").value;\n");
		header.append("    if (sessionId==null || sessionId.trim().length==0) {\n");
		header.append("        sessionId = ZIDS.speaker.generateSessionId();\n");
		header.append("    }\n");
		header.append("    if (context==null || context.trim().length==0) {\n");
		header.append("        context = \"\";\n");
		header.append("    }\n");
		header.append("    var request = ZIDS.dialog.getNewSessionProcessInputRequest(sessionId,input);\n");
		header.append("    if (context.length>0) {\n");
		header.append("        request.context = context;\n");
		header.append("    }\n");
		header.append("    ZIDS.xhr.postJSON(\"../dialog/\",JSON.stringify(request),ZIDS.speaker.postRequestCallback);\n");
		header.append("};\n");
		header.append("ZIDS.speaker.focusInput = function() {\n");
		header.append("    var elem = window.document.getElementById(\"input\");\n");
		header.append("    if (elem!=null) {\n");
		header.append("        elem.blur();\n");
		header.append("        elem.focus();\n");
		header.append("    }\n");
		header.append("};\n");
		header.append("ZIDS.speaker.resetPreviousInput = function() {\n");
		header.append("    var elem = window.document.getElementById(\"input\");\n");
		header.append("    if (elem!=null) {\n");
		header.append("        if (elem.value!=ZIDS.speaker.previousInput) {\n");
		header.append("            ZIDS.speaker.currentInput = elem.value;\n");
		header.append("        }\n");
		header.append("        elem.value = ZIDS.speaker.previousInput;\n");
		header.append("    }\n");
		header.append("};\n");
		header.append("ZIDS.speaker.resetCurrentInput = function() {\n");
		header.append("    var elem = window.document.getElementById(\"input\");\n");
		header.append("    if (elem!=null) {\n");
		header.append("        if (elem.value==ZIDS.speaker.previousInput) {\n");
		header.append("            elem.value = ZIDS.speaker.currentInput;\n");
		header.append("        }\n");
		header.append("    }\n");
		header.append("};\n");
		header.append("ZIDS.speaker.onload = function() {\n");
		header.append("    ZIDS.dom.bindEnterFunctionToElementId(\"input\",ZIDS.speaker.postRequest);\n");
		header.append("    ZIDS.dom.bindCursorUpFunctionToElementId(\"input\",ZIDS.speaker.resetPreviousInput);\n");
		header.append("    ZIDS.dom.bindCursorDownFunctionToElementId(\"input\",ZIDS.speaker.resetCurrentInput);\n");
		header.append("    ZIDS.speaker.focusInput();\n");
		header.append("};\n");
		header.append("</script>");
		
		StringBuilder body = new StringBuilder();
		body.append("<div>");
		body.append("<textarea id=\"log\" >");
		body.append("</textarea>");
		body.append("</div>");
		body.append("<div>\n");
		body.append("<table width=\"100%\">\n");
		body.append("<tr>\n");
		body.append("<td width=\"1%\">\n");
		body.append("Show&nbsp;thoughts&nbsp;");
		body.append("</td>\n");
		body.append("<td width=\"99%\">\n");
		body.append("<input type=\"checkbox\" id=\"showThoughts\" onchange=\"ZIDS.speaker.toggleShowThoughts();\"/>&nbsp;");
		body.append("</td>\n");
		body.append("</tr>\n");
		body.append("<tr>\n");
		body.append("<td>\n");
		body.append("Session&nbsp;ID&nbsp;");
		body.append("</td>\n");
		body.append("<td>\n");
		body.append("<input type=\"text\" id=\"sessionId\"/>&nbsp;");
		body.append("<input type=\"button\" value=\"New\" onclick=\"ZIDS.speaker.newSession();\"/>");
		body.append("</td>\n");
		body.append("</tr>\n");
		body.append("<tr>\n");
		body.append("<td>\n");
		body.append("Context&nbsp;");
		body.append("</td>\n");
		body.append("<td>\n");
		body.append("<input type=\"text\" id=\"context\" class=\"textInput\" />");
		body.append("</td>\n");
		body.append("</tr>\n");
		body.append("<tr>\n");
		body.append("<td>\n");
		body.append("Input&nbsp;");
		body.append("</td>\n");
		body.append("<td>\n");
		body.append("<input type=\"text\" value=\"Hello\" id=\"input\" class=\"textInput\" /><br />");
		body.append("</td>\n");
		body.append("</tr>\n");
		body.append("<tr>\n");
		body.append("<td>\n");
		body.append("</td>\n");
		body.append("<td>\n");
		body.append("<input type=\"button\" value=\"Say\" onclick=\"ZIDS.speaker.postRequest();\"  />");
		body.append("</td>\n");
		body.append("</tr>\n");
		body.append("</table>\n");
		body.append("</div>\n");
		
		HTMLFile f = getNewHTMLFile();
		f.getScriptFiles().add("../ZIDS.js");
		f.getStyleFiles().add("../ZIDS.css");
		f.getHeadElements().add(header.toString());
		f.getBodyElements().add(getMenuForPage("../","","").toString());
		f.getBodyElements().add(body.toString());
		f.setOnload("ZIDS.speaker.onload();");
		return f.toStringBuilder();
	}
}
