package nl.zeesoft.zodb.mod.resource;

import nl.zeesoft.zdk.ZStringBuilder;

public class JavaScriptZODB {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		script.append("var ZODB = ZODB || {};\n");
		
		script.append("\n");
		script.append("ZODB.xhr = {};\n");
		script.append("ZODB.xhr.onReadyStateChange = function(xhr,successCallback,errorCallback) {\n");
		script.append("    if (xhr.readyState == 4) {\n");
		script.append("        if (xhr.status == 200) {\n");
		script.append("            successCallback(xhr);\n");
		script.append("        } else if (errorCallback!=null) {\n");
		script.append("            errorCallback(xhr);\n");
		script.append("        } else {\n");
		script.append("            ZODB.xhr.defaultErrorCallback(xhr);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.xhr.getJSON = function(url,successCallback,errorCallback) {\n");
		script.append("    var xhr = new XMLHttpRequest();\n");
		script.append("    xhr.onreadystatechange = function() {\n");
		script.append("        ZODB.xhr.onReadyStateChange(this,successCallback,errorCallback);\n");
		script.append("    }\n");
		script.append("    xhr.open(\"GET\",url,true);\n");
		script.append("    xhr.setRequestHeader(\"Content-type\",\"application/json\");\n");
		script.append("    xhr.send();\n");
		script.append("    return xhr;\n");
		script.append("};\n");
		script.append("ZODB.xhr.postJSON = function(url,json,successCallback,errorCallback) {\n");
		script.append("    var xhr = new XMLHttpRequest();\n");
		script.append("    xhr.onreadystatechange = function() {\n");
		script.append("        ZODB.xhr.onReadyStateChange(this,successCallback,errorCallback);\n");
		script.append("    }\n");
		script.append("    xhr.open(\"POST\",url,true);\n");
		script.append("    xhr.setRequestHeader(\"Content-type\",\"application/json\");\n");
		script.append("    xhr.send(JSON.stringify(json));\n");
		script.append("    return xhr;\n");
		script.append("};\n");
		script.append("ZODB.xhr.defaultErrorCallback = function(xhr) {\n");
		script.append("    console.error(\"Post request response error: \" + xhr.status + \" \" + xhr.responseText);\n");
		script.append("};\n");
		script.append("ZODB.xhr.parseResponseJSON = function(text) {\n");
		script.append("    var json = JSON.parse(text);\n");
		script.append("    json = ZODB.xhr.correctJSONValues(json);\n");
		script.append("    return json;\n");
		script.append("};\n");
		script.append("ZODB.xhr.correctJSONValues = function(value) {\n");
		script.append("    if (typeof(value)==\"object\") {\n");
		script.append("        var copy = {};\n");
		script.append("        for (var id in value) {\n");
		script.append("            copy[id] = ZODB.xhr.correctJSONValues(value[id]);\n");
		script.append("        }\n");
		script.append("        value = copy;\n");
		script.append("    } else if (typeof(value)==\"string\") {\n");
		script.append("        value = value.replace(/<NEWLINE>/g,\"\\n\");\n");
		script.append("        value = value.replace(/<QUOTE>/g,\"\\\"\");\n");
		script.append("    }\n");
		script.append("    return value;\n");
		script.append("};\n");
		
		script.append("\n");
		script.append("ZODB.dom = {};\n");
		script.append("ZODB.dom.enterFunctions = {};\n");
		script.append("ZODB.dom.cursorUpFunctions = {};\n");
		script.append("ZODB.dom.cursorDownFunctions = {};\n");
		script.append("ZODB.dom.bindEnterFunctionToElementId = function(id,bindFunction) {\n");
		script.append("    ZODB.dom.enterFunctions[id] = bindFunction;\n");
		script.append("};\n");
		script.append("ZODB.dom.bindCursorUpFunctionToElementId = function(id,bindFunction) {\n");
		script.append("    ZODB.dom.cursorUpFunctions[id] = bindFunction;\n");
		script.append("};\n");
		script.append("ZODB.dom.bindCursorDownFunctionToElementId = function(id,bindFunction) {\n");
		script.append("    ZODB.dom.cursorDownFunctions[id] = bindFunction;\n");
		script.append("};\n");
		script.append("ZODB.dom.handleKeyPress = function(event) {\n");
		script.append("    var elem = event.target || event.srcElement;\n");
		script.append("    if (elem!=null && elem.id!=null) {\n");
		script.append("        if (event.keyCode==13 && ZODB.dom.enterFunctions[elem.id]!=null) {\n");
		script.append("            ZODB.dom.enterFunctions[elem.id]();\n");
		script.append("        } else if (event.keyCode==38 && ZODB.dom.cursorUpFunctions[elem.id]!=null) {\n");
		script.append("            ZODB.dom.cursorUpFunctions[elem.id]();\n");
		script.append("        } else if (event.keyCode==40 && ZODB.dom.cursorDownFunctions[elem.id]!=null) {\n");
		script.append("            ZODB.dom.cursorDownFunctions[elem.id]();\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("window.document.onkeypress = ZODB.dom.handleKeyPress;\n");
		script.append("ZODB.dom.selectRadioByElementName = function(name,value) {\n");
		script.append("    var elems = window.document.getElementsByName(name);\n");
		script.append("    if (elems!=null && elems.length>0) {\n");
		script.append("        for (var i = 0; i < elems.length; i++) {\n");
		script.append("            if (elems[i].value==value) {\n");
		script.append("                elems[i].checked = true;\n");
		script.append("            } else {\n");
		script.append("                elems[i].checked = false;\n");
		script.append("            }\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.dom.getSelectedRadioByElementName = function(name) {\n");
		script.append("    var value = null;\n");
		script.append("    var elems = window.document.getElementsByName(name);\n");
		script.append("    if (elems!=null && elems.length>0) {\n");
		script.append("        for (var i = 0; i < elems.length; i++) {\n");
		script.append("            if (elems[i].checked) {\n");
		script.append("                value = elems[i].value;\n");
		script.append("            }\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("    return value;\n");
		script.append("};\n");
		
		script.append("ZODB.encode = {};\n");
		script.append("ZODB.encode.encodeAscii = function(str) {\n");
		script.append("    if (str==null || str.length==0) {\n");
		script.append("        return \"\"\n");
		script.append("    }\n");
		script.append("    var r = \"\";\n");
		script.append("    var ascVals = [];\n");
		script.append("    var avg = 0;\n");
		script.append("    for (var i = 0; i < str.length; i++) {\n");
		script.append("        ascVals[i] = str.substring(i,i+1).charCodeAt(0);\n");
		script.append("        avg += ascVals[i];\n");
		script.append("    }\n");
		script.append("    var key = Math.floor((avg / str.length) / 2);\n");
		script.append("    r += key;\n");
		script.append("    var pKey = key;\n");
		script.append("    for (var i = 0; i < ascVals.length; i++) {\n");
		script.append("        var iKey = key + (((i + 1) * pKey * 7) % 24);\n");
		script.append("        pKey = iKey;\n");
		script.append("        r += \",\";\n");
		script.append("        if (ascVals[i]==iKey) {\n");
	    script.append("            r += \"0\";\n");
	    script.append("        } else if (ascVals[i]>iKey) {\n");
	    script.append("            r += (ascVals[i] - iKey);\n");
	    script.append("        } else if (ascVals[i]<iKey) {\n");
	    script.append("            r += \"-\";\n");
	    script.append("            r += (iKey - ascVals[i]);\n");
	    script.append("        }\n");
		script.append("    }\n");
		script.append("    return r;\n");
		script.append("};\n");
		script.append("ZODB.encode.decodeAscii = function(str) {\n");
		script.append("    if (str==null || str.length==0) {\n");
		script.append("        return \"\"\n");
		script.append("    }\n");
		script.append("    var r = \"\";\n");
		script.append("    var keyVals = str.split(\",\");\n");
		script.append("    if (keyVals.length>=2) {\n");
		script.append("        var key = parseInt(keyVals[0]);\n");
		script.append("        var pKey = key;\n");
		script.append("        for (var i = 1; i < keyVals.length; i++) {\n");
		script.append("            var iKey = key + ((i * pKey * 7) % 24);\n");
		script.append("            pKey = iKey;\n");
		script.append("            var iVal = iKey;\n");
		script.append("            var v = parseInt(keyVals[i]);\n");
		script.append("            if (v>0) {\n");
		script.append("                iVal = iVal + v;\n");							
		script.append("            } else if (v<0) {\n");
		script.append("                iVal = iVal - (v * -1);\n");							
		script.append("            }\n");
		script.append("            r += String.fromCharCode(iVal);\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("    return r;\n");
		script.append("};\n");
		
		return script;
	}
}
