package nl.zeesoft.zodb.mod.resource;

import nl.zeesoft.zdk.ZStringBuilder;
import nl.zeesoft.zodb.db.idx.IndexRequest;
import nl.zeesoft.zodb.mod.ModZODB;
import nl.zeesoft.zodb.mod.handler.JsonZODBIndexConfigHandler;

public class JavaScriptZODBIndexManager {
	public ZStringBuilder toStringBuilder() {
		ZStringBuilder script = new ZStringBuilder();
		
		String path = "../" + ModZODB.NAME + JsonZODBIndexConfigHandler.PATH;
		
		script.append("var ZODB = ZODB || {};\n");
		script.append("ZODB.im = ZODB.im || {};\n");
		script.append("ZODB.im.indexConfig = null;\n");
		script.append("ZODB.im.refresh = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + IndexRequest.TYPE_GET + "\";\n");
		script.append("    ZODB.xhr.postJSON(\"" + path + "\",request,ZODB.im.refreshCallback,ZODB.im.refreshCallback);\n");
		script.append("};\n");
		script.append("ZODB.im.refreshCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else  {\n");
		script.append("        ZODB.im.indexConfig = object;\n");
		script.append("        ZODB.im.showList();\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.im.showList = function() {\n");
		script.append("    var html=\"\";\n");
		script.append("    html+='<table style=\"width: 100%;\">';\n");
		script.append("        html+=\"<tr>\";\n");
		script.append("        html+='<th align=\"left\" width=\"70%\">';\n");
		script.append("        html+=\"Name\";\n");
		script.append("        html+=\"</th>\";\n");
		script.append("        html+='<th align=\"left\" width=\"10%\">';\n");
		script.append("        html+=\"Numeric\";\n");
		script.append("        html+=\"</th>\";\n");
		script.append("        html+='<th align=\"left\" width=\"10%\">';\n");
		script.append("        html+=\"Unique\";\n");
		script.append("        html+=\"</th>\";\n");
		script.append("        html+='<th align=\"left\">';\n");
		script.append("        html+=\"</th>\";\n");
		script.append("        html+=\"</tr>\";\n");
		script.append("    html+=\"<tbody>\";\n");
		script.append("    var listed = 0;\n");
		script.append("    for (var num in ZODB.im.indexConfig.indexes) {\n");
		script.append("        var obj = ZODB.im.indexConfig.indexes[num];\n");
		script.append("        var name = obj.objectNamePrefix + \":\" + obj.propertyName;\n");
		script.append("        var esc = \"'\" + name + \"'\";\n");
		script.append("        var bg = \"\";\n");
		script.append("        if (listed % 2 == 0) {\n");
		script.append("            bg = ' bgcolor=\"" + HtmlResource.HIGHLIGHT_COLOR + "\"';\n");
		script.append("        }\n");
		script.append("        html+=\"<tr>\";\n");
		script.append("        html+='<td' + bg + '>';\n");
		script.append("        html+= name;\n");
		script.append("        html+=\"</td>\";\n");
		script.append("        html+='<td' + bg + '>';\n");
		script.append("        html+= obj.numeric;\n");
		script.append("        html+=\"</td>\";\n");
		script.append("        html+='<td' + bg + '>';\n");
		script.append("        html+= obj.unique;\n");
		script.append("        html+=\"</td>\";\n");
		script.append("        html+='<td' + bg + '>';\n");
		script.append("        html+='<input type=\"button\" value=\"Remove\" onclick=\"ZODB.im.remove(' + esc + ');\" />';\n");
		script.append("        html+='<input type=\"checkbox\" id=\"' + name + '\" />';\n");
		script.append("        html+=\"</td>\";\n");
		script.append("        html+=\"</tr>\";\n");
		script.append("        listed++;\n");
		script.append("    }\n");
		script.append("    html+=\"</tbody>\";\n");
		script.append("    html+=\"</table>\";\n");
		script.append("    html+=\"</div>\";\n");
		script.append("    html+=\"<br />\";\n");
		script.append("    html+=\"</div>\";\n");
		script.append("    if (listed==0) {\n");
		script.append("        html = \"\";\n");
		script.append("    }\n");
		script.append("    var elem = window.document.getElementById(\"list\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        elem.innerHTML = html;\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.im.remove = function(name) {\n");
		script.append("    var elem = window.document.getElementById(name);\n");
		script.append("    if (elem!=null && elem.checked) {\n");
		script.append("        elem.checked = false;\n");
		script.append("        var request = {};\n");
		script.append("        request.type = \"" + IndexRequest.TYPE_REMOVE + "\";\n");
		script.append("        request.name = name;\n");
		script.append("        ZODB.xhr.postJSON(\"" + path + "\",request,ZODB.im.defaultCallback,ZODB.im.defaultCallback);\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.im.add = function() {\n");
		script.append("    var request = {};\n");
		script.append("    request.type = \"" + IndexRequest.TYPE_ADD + "\";\n");
		script.append("    var elem = window.document.getElementById(\"objectNamePrefix\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        request.objectNamePrefix = elem.value;\n");
		script.append("    }\n");
		script.append("    var elem = window.document.getElementById(\"propertyName\");\n");
		script.append("    if (elem!=null) {\n");
		script.append("        request.propertyName = elem.value;\n");
		script.append("    }\n");
		script.append("    var elem = window.document.getElementById(\"numeric\");\n");
		script.append("    if (elem!=null && elem.checked) {\n");
		script.append("        request.numeric = true;\n");
		script.append("    } else {\n");
		script.append("        request.numeric = false;\n");
		script.append("    }\n");
		script.append("    var elem = window.document.getElementById(\"unique\");\n");
		script.append("    if (elem!=null && elem.checked) {\n");
		script.append("        request.unique = true;\n");
		script.append("    } else {\n");
		script.append("        request.unique = false;\n");
		script.append("    }\n");
		script.append("    ZODB.xhr.postJSON(\"" + path + "\",request,ZODB.im.addCallback,ZODB.im.addCallback);\n");
		script.append("};\n");
		script.append("ZODB.im.defaultCallback = function(xhr) {\n");
		script.append("    var response = xhr.responseText;\n");
		script.append("    var object = ZODB.xhr.parseResponseJSON(response);\n");
		script.append("    if (object.error) {\n");
		script.append("        alert(object.error);\n");
		script.append("    } else if (object.errors) {\n");
		script.append("        alert(object.errors[0]);\n");
		script.append("    } else {\n");
		script.append("        ZODB.im.refresh();\n");
		script.append("    }\n");
		script.append("    return object;\n");
		script.append("};\n");
		script.append("ZODB.im.addCallback = function(xhr) {\n");
		script.append("    var object = ZODB.im.defaultCallback(xhr);\n");
		script.append("    if (!object.error && !object.errors) {\n");
		script.append("        var elem = window.document.getElementById(\"objectNamePrefix\");\n");
		script.append("        if (elem!=null) {\n");
		script.append("            elem.value = \"\";\n");
		script.append("        }\n");
		script.append("        var elem = window.document.getElementById(\"propertyName\");\n");
		script.append("        if (elem!=null) {\n");
		script.append("            elem.value = \"\";\n");
		script.append("        }\n");
		script.append("        var elem = window.document.getElementById(\"numeric\");\n");
		script.append("        if (elem!=null && elem.checked) {\n");
		script.append("            elem.checked = false;\n");
		script.append("        }\n");
		script.append("        var elem = window.document.getElementById(\"unique\");\n");
		script.append("        if (elem!=null && elem.checked) {\n");
		script.append("            elem.checked = false;\n");
		script.append("        }\n");
		script.append("    }\n");
		script.append("};\n");
		script.append("ZODB.im.onload = function() {\n");
		script.append("    ZODB.im.refresh();\n");
		script.append("};\n");
		
		return script;
	}
}
