package nl.zeesoft.zdbd.api.javascript;

import nl.zeesoft.zdbd.api.ResponseObject;
import nl.zeesoft.zdk.Str;

public class ArpeggiatorsJs extends ResponseObject {
	@Override
	public Str render() {
		Str r = new Str();
		append(r,"var arpeggiators = arpeggiators || {};");
		append(r,"arpeggiators.editName = \"\";");
		append(r,"arpeggiators.showList = false;");
		append(r,"arpeggiators.refresh = function() {");
		append(r,"    if (arpeggiators.showList) {");
		append(r,"        main.xhr.getText(\"/arpeggiators.txt\",arpeggiators.refreshCallback,arpeggiators.errorCallback);");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.refreshCallback = function(response) {");
		append(r,"    var elem = window.document.getElementById(\"arpeggiatorList\");");
		append(r,"    if (elem!=null && arpeggiators.showList) {");
		append(r,"        elem.innerHTML = response.responseText;");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.errorCallback = function(response) {");
		append(r,"    if (response.status==503) {");
		append(r,"        setTimeout(function() { arpeggiators.refresh(); }, 500);");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.clear = function() {");
		append(r,"    var elem = window.document.getElementById(\"arpeggiatorList\");");
		append(r,"    if (elem!=null) {");
		append(r,"        elem.innerHTML = \"\";");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.toggleShowList = function(property) {");
		append(r,"    arpeggiators.showList = !arpeggiators.showList;");
		append(r,"    if (arpeggiators.showList) {");
		append(r,"        main.dom.startFadeIn(\"arpeggiatorList\");");
		append(r,"        arpeggiators.refresh();");
		append(r,"        property.value = \"-\";");
		append(r,"    } else {");
		append(r,"        arpeggiators.clear();");
		append(r,"        property.value = \"+\";");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.delete = function(name) {");
		append(r,"    var d = confirm(\"Are you sure you want to delete the arpeggiator?\");");
		append(r,"    if (d==true) {");
		append(r,"        var cb = function() { arpeggiators.refresh(); sequencer.refresh(); };");
		append(r,"        main.xhr.postText(\"/arpeggiators.txt\",\"DELETE:\" + name,cb,main.xhr.alertErrorCallback);");
		append(r,"    }");
		append(r,"};");
		append(r,"arpeggiators.edit = function(name) {");
		append(r,"    arpeggiators.editName = name;");
		append(r,"    main.xhr.postText(\"/arpeggiator.txt\",\"EDIT:\" + name,arpeggiators.editCallback,main.xhr.alertErrorCallback);");
		append(r,"};");
		append(r,"arpeggiators.editCallback = function(response) {");
		append(r,"    modal.loadCallback(response);");
		append(r,"};");
		append(r,"arpeggiators.editDone = function() {");
		append(r,"    arpeggiators.refresh();");
		append(r,"    sequencer.refresh();");
		append(r,"    modal.hide();");
		append(r,"};");
		append(r,"arpeggiators.propertyChange = function(property) {");
		append(r,"    if (property.id==\"name\" && property.value.length==0) {");
		append(r,"        alert(\"Arpeggiator name is mandatory\");");
		append(r,"        return;");
		append(r,"    }");
		append(r,"    var body = \"SET_PROPERTY:\";");
		append(r,"    body += arpeggiators.editName;");
		append(r,"    body += \":\";");
		append(r,"    body += property.id;");
		append(r,"    body += \":\";");
		append(r,"    body += main.dom.getElementValue(property.id);");
		append(r,"    var cb = null;");
		append(r,"    if (property.id==\"name\") {");
		append(r,"        cb = function() { arpeggiators.editName = property.value; arpeggiators.refresh(); };");
		append(r,"    }");
		append(r,"    main.xhr.postText(\"/arpeggiator.txt\",body,cb,main.xhr.alertErrorCallback);");
		append(r,"}");
		append(r,"arpeggiators.add = function() {");
		append(r,"    arpeggiators.editName = \"\";");
		append(r,"    main.xhr.postText(\"/arpeggiator.txt\",\"ADD\",arpeggiators.editCallback,main.xhr.alertErrorCallback);");
		append(r,"};");
		append(r,"arpeggiators.addCancel = function() {");
		append(r,"    modal.hide();");
		append(r,"};");
		append(r,"arpeggiators.addDone = function() {");
		append(r,"    var name = main.dom.getElementValue(\"name\");");
		append(r,"    if (name==null || name.length==0) {");
		append(r,"        alert(\"Generator name is mandatory\");");
		append(r,"        return;");
		append(r,"    }");
		append(r,"    var ids = [\"name\",\"minDuration\",\"maxDuration\",\"density\",\"maxOctave\",\"maxInterval\",\"maxSteps\"];");
		append(r,"    var obj = main.dom.buildBodyText(ids);");
		append(r,"    var cb = function() { modal.hide(); arpeggiators.refresh(); sequencer.refresh(); };");
		append(r,"    main.xhr.postText(\"/arpeggiator.txt\",\"SAVE\\n\" + obj,cb,main.xhr.alertErrorCallback);");
		append(r,"};");
		return r;
	}
}
