package nl.zeesoft.zdbd.api.javascript;

import nl.zeesoft.zdbd.api.ResponseObject;
import nl.zeesoft.zdk.Str;

public class SequencerJs extends ResponseObject {
	@Override
	public Str render() {
		Str r = new Str();
		append(r,"var sequencer = sequencer || {};");
		append(r,"sequencer.refresh = function() {");
		append(r,"    main.xhr.getText(\"/sequencerControl.txt\",sequencer.refreshCallback,sequencer.errorCallback);");
		append(r,"    sequencer.refreshState();");
		append(r,"};");
		append(r,"sequencer.refreshCallback = function(response) {");
		//append(r,"    console.log(response);");
		append(r,"    var elem = window.document.getElementById(\"sequencer\");");
		append(r,"    if (elem!=null) {");
		append(r,"        elem.innerHTML = response.responseText;");
		append(r,"    }");
		append(r,"};");
		append(r,"sequencer.errorCallback = function(response) {");
		append(r,"    if (response.status==503) {");
		append(r,"        setTimeout(function() { sequencer.refresh(); }, 500);");
		append(r,"    }");
		append(r,"};");
		append(r,"sequencer.refreshState = function() {");
		append(r,"    main.xhr.getText(\"/sequencer.txt\",sequencer.refreshStateCallback,sequencer.errorStateCallback);");
		append(r,"};");
		append(r,"sequencer.refreshStateCallback = function(response) {");
		//append(r,"    console.log(response);");
		append(r,"    var obj = main.xhr.parseResponseText(response.responseText);");
		//append(r,"    console.log(obj);");
		append(r,"    var elem = window.document.getElementById(\"currentSequence\");");
		append(r,"    if (elem!=null && elem.options[elem.selectedIndex].value!=obj.currentSequence) {");
		append(r,"        elem.value = obj.currentSequence;");
		append(r,"    }");
		append(r,"    var elem = window.document.getElementById(\"nextSequence\");");
		append(r,"    if (elem!=null && elem.options[elem.selectedIndex].value!=obj.nextSequence) {");
		append(r,"        elem.value = obj.nextSequence;");
		append(r,"    }");
		append(r,"    if (obj.isRunning) {");
		append(r,"        setTimeout(function() { sequencer.refreshState(); }, 200);");
		append(r,"    }");
		append(r,"};");
		append(r,"sequencer.errorStateCallback = function(response) {");
		append(r,"    if (response.status==503) {");
		append(r,"        setTimeout(function() { sequencer.refreshState(); }, 500);");
		append(r,"    }");
		append(r,"};");
		append(r,"sequencer.clear = function() {");
		append(r,"    var elem = window.document.getElementById(\"sequencer\");");
		append(r,"    if (elem!=null) {");
		append(r,"        elem.innerHTML = \"\";");
		append(r,"    }");
		append(r,"};");
		append(r,"sequencer.propertyChange = function(property) {");
		append(r,"    var body = \"SET_PROPERTY:\";");
		append(r,"    body += property.id;");
		append(r,"    body += \":\";");
		append(r,"    body += main.dom.getElementValue(property.id);");
		append(r,"    var cb = null;");
		append(r,"    if (property.id==\"beatsPerMinute\") {");
		append(r,"        cb = function() { theme.refresh(); };");
		append(r,"    } else if (property.id.indexOf(\"Sequence\")>0) {");
		append(r,"        cb = function() { sequencer.refresh(); };");
		append(r,"    } else if (property.type==\"checkbox\") {");
		append(r,"        cb = function() { sequencer.refresh(); };");
		append(r,"    }");
		append(r,"    main.xhr.postText(\"/sequencer.txt\",body,cb);");
		append(r,"}");
		append(r,"sequencer.startSequence = function() {");
		append(r,"    main.xhr.postText(\"/sequencer.txt\",\"START_SEQUENCE\",sequencer.refresh,main.xhr.alertErrorCallback);");
		append(r,"}");
		append(r,"sequencer.startTheme = function() {");
		append(r,"    main.xhr.postText(\"/sequencer.txt\",\"START\",sequencer.refresh,main.xhr.alertErrorCallback);");
		append(r,"}");
		append(r,"sequencer.stop = function() {");
		append(r,"    main.xhr.postText(\"/sequencer.txt\",\"STOP\",sequencer.refresh,main.xhr.alertErrorCallback);");
		append(r,"}");
		return r;
	}
}
